---
- name: Install VNC TigerVNC server
  hosts: jump-host
  become: yes
  pre_tasks:
    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest
    - name: Install EPEL release repository
      dnf:
        name: epel-release
        state: present
    - name: Install Xfce GUI environment
      dnf:
        name:
          - '@Xfce'
          - '@base-x'
        state: present
    - name: Get current systemd default
      command: systemctl get-default
      changed_when: false
      register: systemddefault
    - name: Set graphical environment
      command: systemctl set-default graphical
      become: yes
      when: "'graphical' not in systemddefault.stdout"
      notify:
        - Reboot
  tasks:
    - name: Install TigerVNC package
      dnf:
        name: tigervnc-server
        state: present
  handlers:
    - name: Reboot
      reboot:

- name: Configure VNC server
  hosts: jump-host
  become: yes
  pre_tasks:
    - name: Create an user for VNC
      user:
        comment: User for VNC
        create_home: true
        name: "{{ tigervnc_user }}"
        shell: /bin/bash
        groups: wheel
        append: yes
        password: "{{ tigervnc_pass | password_hash('sha512', 'mysecretsalt') }}"
  tasks:
    - name: Set vncuser password using vncpasswd
      shell:
        cmd: set -o pipefail ; printf "{{ tigervnc_pass }}\n{{ tigervnc_pass }}\n" | vncpasswd
        creates: /home/{{ tigervnc_user }}/.vnc/passwd
        executable: /bin/bash
      become: yes
      become_user: "{{ tigervnc_user }}"
    - name: Copy unit file
      copy:
        src: /lib/systemd/system/vncserver@.service
        dest: /etc/systemd/system/vncserver@:1.service
        remote_src: yes
    - name: Map users to displays
      lineinfile:
        path: /etc/tigervnc/vncserver.users
        line: :1={{ tigervnc_user }}
    - name: Make sure vncserver is running
      systemd:
        daemon_reload: yes
        name: 'vncserver@:1'
        enabled: yes
        state: started
    - name: Open vncserver port through firewall
      firewalld:
        service: vnc-server
        permanent: yes
        zone: public
        state: enabled

- name: Update network configuration to use new dns server
  hosts: jump-host
  become: yes
  tasks:
    - name: Update DNS information
      community.general.nmcli:
        type: ethernet
        conn_name: eth0
        method4: auto
        dns4_ignore_auto: true
        dns4: '10.1.2.5'
        dns4_search:
          - vmware.ibmcloud.local
          - nsb.local
        state: present


- name: Install essential tools
  hosts: jump-host
  become: yes
  pre_tasks:
    - name: Add terraform repo
      command: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      args: 
        creates: /etc/yum.repos.d/hashicorp.repo
  tasks:
    - name: Install essential tools
      dnf:
        name:
          - bind-utils
          - tmux
          - git
          - tree
          - vim
          - libnsl
          - aria2
          - unzip
          - firefox
          - p7zip
          - terraform
          - ruby
        state: present
      tags:
        - packages
    - name: Install mkpasswd ruby gem
      community.general.gem:
        name: mkpasswd
        state: latest
        user_install: false